version: "3.1"

services:
  db:
    container_name: ficaespertoapp_db
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_DB=ficaespertoapp
      - POSTGRES_PASSWORD=ficaespertoapp
      - POSTGRES_USER=ficaespertoapp
    ports:
      - "5432:5432"