spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/ficaespertoapp
    username: ficaespertoapp
    password: ficaespertoapp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    key: 37E6A2D46FF8C566756E25EA5B4FD37E6A2D46FF8C566756E25EA5B4FD

server:
  port: 8080