spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/ficaespertoapp
    username: ficaespertoapp
    password: ficaespertoapp
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      platform: mysql

security:
  jwt:
    key: 37E6A2D46FF8C566756E25EA5B4FD37E6A2D46FF8C566756E25EA5B4FD

server:
  port: 8080